<?php
/**
 * @var \Himanshu\Blog\Block\Index $block
 * 
 * Blog Post List
 */
?>
<?php echo $block->printMessage(); ?> 
<section class="blog-posts">
    <div class="post-header">
<?php echo __("Total Posts : %1", 10) ?>
    </div>

    <div class="post-lists">
        <article itemscope itemtype="https://schema.org/CreativeWork">
            <h3 itemprop="headline">Post Title 1</h3>
            <img itemprop="thumbnailUrl" src="http://10.16.16.243/magento2/pub/media/himanshu_blog/post/default_placeholder.jpg" height="250" width="280" title="Feature Image Of Post Title 1"/>
            <p>
                <strong itemprop="author" itemscope itemtype="http://schema.org/Person"><?php echo __("By") ?> Himanshu</strong>
                <time itemprop="datePublished" datetime="2018-09-26"><?php echo __("on") ?>  26 Sep 2018</time>
            </p>
            <p itemprop="text">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.</p>
        </article>
        <article itemscope itemtype="https://schema.org/CreativeWork">
            <h3 itemprop="headline">Post Title 1</h3>
            <img itemprop="thumbnailUrl" src="http://10.16.16.243/magento2/pub/media/himanshu_blog/post/default_placeholder.jpg" height="250" width="280" title="Feature Image Of Post Title 1"/>
            <p>
                <strong itemprop="author" itemscope itemtype="http://schema.org/Person"><?php echo __("By") ?> Himanshu</strong>
                <time itemprop="datePublished" datetime="2018-09-26"><?php echo __("on") ?>  26 Sep 2018</time>
            </p>
            <p itemprop="text">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.</p>
        </article>
        <article itemscope itemtype="https://schema.org/CreativeWork">
            <h3 itemprop="headline">Post Title 1</h3>
            <img itemprop="thumbnailUrl" src="http://10.16.16.243/magento2/pub/media/himanshu_blog/post/default_placeholder.jpg" height="250" width="280" title="Feature Image Of Post Title 1"/>
            <p>
                <strong itemprop="author" itemscope itemtype="http://schema.org/Person"><?php echo __("By") ?> Himanshu</strong>
                <time itemprop="datePublished" datetime="2018-09-26"><?php echo __("on") ?>  26 Sep 2018</time>
            </p>
            <p itemprop="text">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.</p>
        </article>
        <article itemscope itemtype="https://schema.org/CreativeWork">
            <h3 itemprop="headline">Post Title 1</h3>
            <img itemprop="thumbnailUrl" src="http://10.16.16.243/magento2/pub/media/himanshu_blog/post/default_placeholder.jpg" height="250" width="280" title="Feature Image Of Post Title 1"/>
            <p>
                <strong itemprop="author" itemscope itemtype="http://schema.org/Person"><?php echo __("By") ?> Himanshu</strong>
                <time itemprop="datePublished" datetime="2018-09-26"><?php echo __("on") ?>  26 Sep 2018</time>
            </p>
            <p itemprop="text">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.</p>
        </article>
        <article itemscope itemtype="https://schema.org/CreativeWork">
            <h3 itemprop="headline">Post Title 1</h3>
            <img itemprop="thumbnailUrl" src="http://10.16.16.243/magento2/pub/media/himanshu_blog/post/default_placeholder.jpg" height="250" width="280" title="Feature Image Of Post Title 1"/>
            <p>
                <strong itemprop="author" itemscope itemtype="http://schema.org/Person"><?php echo __("By") ?> Himanshu</strong>
                <time itemprop="datePublished" datetime="2018-09-26"><?php echo __("on") ?>  26 Sep 2018</time>
            </p>
            <p itemprop="text">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.</p>
        </article>
    </div>

    <div class="post-footer">
        Pagination
    </div>
</section>